// HireMind Recruitment API — Unified exports
export * from './client'
export * as positionsApi from './positions'
export * as candidatesApi from './candidates'
export * as resumesApi from './resumes'
export * as matchingApi from './matching'
export * as interviewsApi from './interviews'
export * as offersApi from './offers'
export * as analyticsApi from './analytics'
export * as departmentsApi from './departments'
export * as tasksApi from './tasks'
export * as dashboardApi from './dashboard'
export * as insightsApi from './insights'
export * as cronApi from './cron'
export * as skillRegistryApi from './skill-registry'
export * as skillsApi from './skills'
export * as scheduledTasksApi from './scheduled-tasks'
export * as dailyReportsApi from './daily-reports'
