"""initial_hiremind_schema

Revision ID: 05b7e71fa93b
Revises: 
Create Date: 2026-05-15 10:46:00.349087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05b7e71fa93b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_path'), 'audit_logs', ['path'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Department code, e.g. ENG, HR'),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('head_user_id', sa.String(length=64), nullable=True, comment='Department head user ID'),
    sa.Column('headcount_limit', sa.Integer(), nullable=True),
    sa.Column('tree_path', sa.String(length=500), nullable=True, comment="Materialized path, e.g. 'tech.backend'"),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name_encrypted', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('positions',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft / open / paused / closed / filled'),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_exp_min', sa.Integer(), nullable=True),
    sa.Column('required_exp_max', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=False),
    sa.Column('profile_summary', sa.Text(), nullable=True),
    sa.Column('profile_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('filled_count', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='Optimistic lock version'),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education_requirement', sa.String(length=100), nullable=True),
    sa.Column('experience_years_min', sa.Integer(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_department_id'), 'positions', ['department_id'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_tenant_id'), 'positions', ['tenant_id'], unique=False)
    op.create_table('candidates',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('name_encrypted', sa.String(length=512), nullable=True, comment='AES-256 encrypted in Phase 2'),
    sa.Column('email_hash', sa.String(length=64), nullable=False, comment='SHA256 of email for dedup'),
    sa.Column('phone_hash', sa.String(length=64), nullable=False, comment='SHA256 of phone for dedup'),
    sa.Column('name_hash', sa.String(length=64), nullable=True, comment='SHA256 of name for fuzzy match'),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='7-category profile: basic_info, education, work_experience, skills, certifications, projects, preferences'),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Source traceability index'),
    sa.Column('credibility_score', sa.Float(), nullable=True, comment='0-100 credibility score'),
    sa.Column('credibility_grade', sa.String(length=1), nullable=True, comment='A(>=80) / B(>=60) / C(>=40) / D(<40)'),
    sa.Column('inference_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI inference results'),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active / inactive / blacklisted / onboarded'),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='Optimistic lock version'),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False, comment='Pipeline stage: applied/screened/interviewed/offered/hired/rejected'),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_detail', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_recruiter', sa.String(length=64), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_hash', 'email_hash', name='uq_candidate_identity')
    )
    op.create_index(op.f('ix_candidates_tenant_id'), 'candidates', ['tenant_id'], unique=False)
    op.create_table('interviews',
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='Interviewed candidate'),
    sa.Column('position_id', sa.UUID(), nullable=True, comment='Position being interviewed for'),
    sa.Column('round_number', sa.Integer(), nullable=False, comment='Interview round (1, 2, 3...)'),
    sa.Column('interview_type', sa.String(length=50), nullable=False, comment='technical / behavioral / hr / final / phone_screen'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='scheduled / in_progress / completed / cancelled / no_show'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True, comment='Scheduled start time'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='Planned duration'),
    sa.Column('location', sa.String(length=512), nullable=True, comment='Physical location or meeting link'),
    sa.Column('interviewer_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of interviewer user IDs'),
    sa.Column('overall_score', sa.Float(), nullable=True, comment='Overall interview score (0-10)'),
    sa.Column('recommendation', sa.String(length=50), nullable=True, comment='strong_yes / yes / no / strong_no'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Interview summary'),
    sa.Column('ai_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI-suggested interview questions'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Actual completion time'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='Cancellation timestamp'),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_index(op.f('ix_interviews_tenant_id'), 'interviews', ['tenant_id'], unique=False)
    op.create_table('matches',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/screening/shortlisted/interview_scheduled/interviewed/offered/hired/rejected/withdrawn'),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('skill_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('education_score', sa.Float(), nullable=True),
    sa.Column('inference_score', sa.Float(), nullable=True),
    sa.Column('salary_score', sa.Float(), nullable=True, comment='Salary match score'),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Detailed score breakdown'),
    sa.Column('match_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Match analysis: strengths/gaps/suggestions'),
    sa.Column('candidate_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Candidate feedback'),
    sa.Column('initiated_by', sa.String(length=20), nullable=False, comment='system/candidate/hr'),
    sa.Column('vector_similarity', sa.Float(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'candidate_id', name='uq_match')
    )
    op.create_index(op.f('ix_matches_candidate_id'), 'matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_matches_position_id'), 'matches', ['position_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_tenant_id'), 'matches', ['tenant_id'], unique=False)
    op.create_table('offers',
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='Candidate receiving the offer'),
    sa.Column('position_id', sa.UUID(), nullable=True, comment='Position for the offer'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft / pending_approval / approved / sent / accepted / rejected / withdrawn'),
    sa.Column('base_salary', sa.Integer(), nullable=True, comment='Base monthly salary'),
    sa.Column('annual_bonus_months', sa.Float(), nullable=True, comment='Annual bonus in months'),
    sa.Column('sign_on_bonus', sa.Integer(), nullable=True, comment='One-time sign-on bonus'),
    sa.Column('equity', sa.String(length=255), nullable=True, comment='Equity / stock options description'),
    sa.Column('benefits_summary', sa.Text(), nullable=True, comment='Benefits package summary'),
    sa.Column('proposed_start_date', sa.DateTime(timezone=True), nullable=True, comment='Proposed start date'),
    sa.Column('probation_months', sa.Integer(), nullable=True, comment='Probation period in months'),
    sa.Column('work_location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True, comment='full_time / contract / etc.'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes'),
    sa.Column('offer_letter_url', sa.String(length=1024), nullable=True, comment='Generated offer letter file URL'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_note', sa.Text(), nullable=True, comment="Candidate's response note"),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True, comment='Offer expiration date'),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_offers_tenant_id'), 'offers', ['tenant_id'], unique=False)
    op.create_table('resumes',
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True, comment='Applied position'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original file name'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='File storage path'),
    sa.Column('file_type', sa.String(length=10), nullable=True, comment='pdf/docx/doc/png/jpg/jpeg'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Bytes'),
    sa.Column('content_type', sa.String(length=128), nullable=False, comment='MIME type'),
    sa.Column('file_hash', sa.String(length=128), nullable=True, comment='SHA-256 for dedup'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='upload/email/boss/referral/headhunter'),
    sa.Column('uploaded_by', sa.String(length=64), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=False, comment='pending/processing/completed/failed'),
    sa.Column('parsed_at', sa.String(length=50), nullable=True, comment='Timestamp when parsing completed'),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI-extracted structured data (immutable audit trail)'),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Field source annotations'),
    sa.Column('credibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Credibility check results'),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False, comment='Optimistic lock version'),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_feedbacks',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('interviewer_id', sa.String(length=64), nullable=False, comment='Interviewer user ID'),
    sa.Column('score', sa.Float(), nullable=False, comment='Score given (0-10)'),
    sa.Column('recommendation', sa.String(length=50), nullable=False, comment='strong_yes / yes / no / strong_no'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='Candidate strengths observed'),
    sa.Column('weaknesses', sa.Text(), nullable=True, comment='Areas of concern'),
    sa.Column('comments', sa.Text(), nullable=True, comment='General comments'),
    sa.Column('skill_ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Per-skill ratings'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_feedback',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False, comment='positive/negative/neutral'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ai_accuracy_score', sa.SmallInteger(), nullable=True, comment='1-5 accuracy rating'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_feedback_match_id'), 'match_feedback', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_feedback_tenant_id'), 'match_feedback', ['tenant_id'], unique=False)
    op.create_table('offer_approvals',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.String(length=64), nullable=False, comment='Approver user ID'),
    sa.Column('approver_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending / approved / rejected'),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_order', sa.Integer(), nullable=False, comment='Order in approval chain'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_approvals')
    op.drop_index(op.f('ix_match_feedback_tenant_id'), table_name='match_feedback')
    op.drop_index(op.f('ix_match_feedback_match_id'), table_name='match_feedback')
    op.drop_table('match_feedback')
    op.drop_table('interview_feedbacks')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_offers_tenant_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_matches_tenant_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_position_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_candidate_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_interviews_tenant_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_candidates_tenant_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_positions_tenant_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_department_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_path'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
